export type ConnectFilters = {
  to: string;
  from: string;
  sliderValue: number;
  date: string;
  activities: string[];
  preference: string[];
  preferenceAge: {
    minimumAge: number;
    maximumAge: number;
  };
};

export type LooseObject = {
  [key: string]: any;
};
export interface Amigo {
  _id: string;
  bio: string;
  birthday: string;
  connectPreferences: ConnectPreferences;
  contact: Contact;
  createdAt: string;
  favorites: string[];
  gender: string;
  hobbies: string[];
  homeCountry: string;
  isVerified: boolean;
  languages: string[];
  name: string;
  updatedAt: string;
}

export interface ConnectPreferences {
  activities: string[];
  currentLocation: CurrentLocation;
  fromDate: string;
  gender: string[];
  isInvisible: boolean;
  maxAge: number;
  minAge: number;
  toDate: string;
}

export interface CurrentLocation {
  latitude: string;
  longitude: string;
}

export interface Contact {
  email: string;
  phoneNumber: string;
}

// Generated by https://quicktype.io

export interface PendingRequestResponse {
  _id: string;
  userID1: Amigo;
  userID2: Amigo;
  isConnected: boolean;
  isPending: boolean;
  createdAt: string;
  updatedAt: string;
  __v: number;
  id: string;
}

export interface ConnectPreferences {
  isInvisible: boolean;
  currentLocation: CurrentLocation;
  locationDistance: number;
  gender: string[];
  minAge: number;
  maxAge: number;
  fromDate: string;
  toDate: string;
  fromTime: number;
  toTime: number;
  activities: string[];
}

export interface CurrentLocation {
  latitude: string;
  longitude: string;
}
